### ISSUE TITLE
Bug: doesn't seem to support gitlab

### ISSUE THREAD

**Issue by jamesla** [aslafy-z/helm-git#281]
Given the following helm chart repo

https://gitlab.com/one-touch-pipeline/weskit/helm-deployment

It's not possible to add as a subchart IE to reproduce

```
dependencies:
  - name: weskit
    version: "0.1.0"
    repository: "git+https://gitlab.com/one-touch-pipeline/weskit/helm-deployment"
```

and running `helm dependency update`

It asks for a username

Assuming this is because of gitlab projects making the URI have 3 sections.

Here is the public repo https://gitlab.com/one-touch-pipeline/weskit/helm-deployment

Is gitlab supported?

**Comment by aslafy-z** [comment]
Hello @jamesla ,

- GitLab is supported.
- You don't specify `ref` option. Before v1.0.0 that was just released today, it was defaulting to `master` which does not exists on your repo, `main` exists however. Now, [default branch is automatically discovered](https://github.com/aslafy-z/helm-git/releases/tag/v1.0.0). 
- "inner-repository" path is not specified.  Before v1.2.0 that was just released today, [path separator (`@`) was mandatory even if empty. Now, if chart(s) are in the root of the repository, [the path separator can be ignored](https://github.com/aslafy-z/helm-git/releases/tag/v1.2.0). 
- [Helm chart version 0.1.0 does not exists at ref 'main'](https://gitlab.com/one-touch-pipeline/weskit/helm-deployment/-/blob/main/Chart.yaml?ref_type=heads#L20)


Please try again with:

`helm-git` version < 1.0.0:

```
dependencies:
  - name: weskit
    version: "0.2.0"
    repository: "git+https://gitlab.com/one-touch-pipeline/weskit/helm-deployment@?ref=main"
```

`helm-git` version > 1.2.0:

```
dependencies:
  - name: weskit
    version: "0.2.0"
    repository: "git+https://gitlab.com/one-touch-pipeline/weskit/helm-deployment"
```

Note that I highly recommend pinning Git hash or at least tags with the `ref` option.

Let me know if it works for you so I can close this issue. 

Regards

**Comment by aslafy-z** [comment]
@jamesla Please reopen the issue if needed.

**Comment by jamesla** [comment]
Thanks @aslafy-z sorry I didn't see your reply.

So I've tried your suggestion with the updated version of helm-git but it's asking me for github credentials - however this is an open source repository. 

You can see it's open source here: https://gitlab.com/one-touch-pipeline/weskit/helm-deployment

```
dependencies:
  - name: weskit
    version: "0.2.0"
    repository: "git+https://gitlab.com/one-touch-pipeline/weskit/helm-deployment@?ref=main"
```

Why is it asking for credentials?
