### ISSUE TITLE
Cleanup conflicting config values

### ISSUE THREAD

**Issue by aslafy-z** [aslafy-z/helm-git#53]
One enhancement that could be added at some point in the future is something that bit me.  I had existing helm defaults for tillerless.

```yaml
helmDefaults:
  tillerless: true
  tillerNamespace: kube-system
  wait: true
```

When helm 3 is used, the command lines built reflect helm tiller plugin usage and fail, but could simply ignore it.  It was an easy fix for me to remove the offending config, however, but may trip others up needlessly, at least in the immediate future when both helm 2 and 3 are being used.

_Originally posted by @mojochao in https://github.com/aslafy-z/helm-git/pull/50#issuecomment-557251299_
